[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ragcore"
version = "0.1.0"
description = "A modular RAG framework for document retrieval and generation."
authors = [
  { name = "Matis Codjia", email = "matis.codjia@epita.fr" }
]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
]
